name: build-deploy-model

on:
  workflow_dispatch:
    inputs:
      imageVersion:
        description: 'Image Version'
        required: true
      targetStageRepo:
        description: 'Target Stage Repo'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - stg
        - prod

env:
  IMAGE_NAME: ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/kde-ecomm-${{ inputs.targetStageRepo }}/ecomm/interpretable-dynamic-rfm-service:v${{ inputs.imageVersion }}

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    permissions: # gcp auth required
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout # prerequisite
        uses: actions/checkout@v4

      - name: Echo Build Detail
        run: |
          echo 'Branch Release: ${{ github.ref_name }}'
          echo 'Image version: ${{ inputs.imageVersion }}'
          echo 'Target Stage Repo: ${{ inputs.targetStageRepo }}'

      - name:  Authenticate GCP - Workload Identity Federation
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          workload_identity_provider: ${{ secrets.WIF_PROVIDER_URL }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - name: Install Dependencies (Setup Cloud SDK)
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '500.0.0'

      - name: Configure Docker Client of gcloud
        run: |
          gcloud auth configure-docker ${{ secrets.REGION }}-docker.pkg.dev

      - name: Docker Build Image
        run: docker build -t ${{ env.IMAGE_NAME }} code/models/

      - name: Docker Push Image
        run: docker push ${{ env.IMAGE_NAME }}
